# Site settings
title: Mikroways
email: contacto@mikroways.net
description: >
  Mikroways es una empresa joven, que brinda soluciones en el campo de la tecnolog&iacute;a
  de la informaci&oacute;n y que se nutre de profesionales altamente capacitados y con
  amplia experiencia en el rubro.
baseurl: "" 
url: "http://www.mikroways.net"
twitter_username: jekyllrb
github_username:  jekyll
social:
  facebook: "https://facebook.com/mikroways"
  github: "https://github.com/mikroways"
  linkedin: "https://www.linkedin.com/company/mikroways"
  twitter: "https://twiter.com/mikroways"

languages: ["es", "en"]

include: ['_posts']

markdown: kramdown
kramdown:
  input: GFM
